version: '3.8'
services:
  web-dinamis:
    image: krisnaadilla19/web-dinamis:latest
    container_name: container-dinamis
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db-webdinamis
      - NEXTAUTH_URL=http://18.141.231.18 
      - NEXTAUTH_SECRET=krisna28_secret_panjang
    depends_on:
      - db-webdinamis

  db-webdinamis:
    image: mariadb:lts
    container_name: db-webdinamis
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password_anda
      MARIADB_DATABASE: dbcompro_2388010044
    volumes:
      - db_data_baru:/var/lib/mysql
      - ./db_data/dbcompro_2388010044.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data_baru: