name: Deploy KRISNA STORE ke AWS

on:
  push:
    branches:
      - main
    paths:
      - 'web-dinamis/**' # Sangat penting untuk efisiensi pipeline (Bobot 20%)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dan Push Image
        run: |
          # Build image dengan tag terbaru
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis:latest ./web-dinamis
          # Push ke Docker Hub agar bisa ditarik oleh AWS
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis:latest

      - name: Deploy ke AWS EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          port: 22
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            # Masuk ke direktori proyek di server
            cd ~/himafor_2388010044
            
            # Pull image versi terbaru
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis:latest
            
            # Re-deploy kontainer (otomatis mengganti yang lama)
            docker-compose up -d --force-recreate
            
            # Membersihkan sisa image lama agar disk tidak penuh
            docker image prune -f